### ISSUE TITLE
Any test script that sends 100~200 requests simultaneously (invokes docker run & DB access)?

### ISSUE THREAD

**Issue by injan0913** [catsass19/Sapporo#26]
The one exists now is just for docker. Also it sends requests one after one, I don't want to initiate 100 browser session on my laptop :P

**Comment by catsass19** [comment]
@fwfly Kenny's script is able to do that, but the difference is that no data is written to db. We tried 100 before and for those requests which exceed the limitation will be rejected immediately by the server.

**Comment by injan0913** [comment]
Ok! You mean the one in performance test page? 
I think we need to try 200(with correct codes & bad codes) this time and make it for 2 hours with 10 seconds interval.
Also we need these requests to invoke DB access. 

This will give us more confidence XD.

**Comment by catsass19** [comment]
There's a folder (.auto_test) under root folder and the script are all in there. It's based on Meteor-Down. You can create any amount of users and they will send request in a given interval. I was wrong about the DB access, "perfornaceTest" method does access db. It logs the result to DB and that's why we are able to see the chart. Is it sufficient for DB testing?
